### PR TITLE
fix(windows): support Windows environment

### LINKED ISSUE #97: Local path resolution failure on Windows platform
When the rule find local file path, it will try to resolve relative uri to a file by [URI.resolve](https://github.com/textlint-rule/textlint-rule-no-dead-link/blob/master/src/no-dead-link.js#L149). On Windows platform, `protocol` property will be drive letter and it causes unexpected fetch call then `node-fetch` throws [`only absolute urls are supported`](https://github.com/bitinn/node-fetch/blob/v1.6.3/index.js#L54) error.

I'm sorry but it is difficult for me to reproduce/fix this issue locally as I have no Windows environment. Please refer to https://github.com/textlint/textlint/pull/442#issuecomment-354599661 for detail.

### PR DESCRIPTION
**Pull request by azu**
Based on #98 

Please merge #98 at first, and merge this secondary.

fix #97

### CODE REVIEW

File: src/no-dead-link.js [hunk 1]
```diff
@@ -16,17 +17,23 @@ const URI_REGEXP = /(?:https?:)?\/\/(?:www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-z
  * Returns `true` if a given URI is relative.
  * @param {string} uri
  * @return {boolean}
+ * @see https://github.com/panosoft/is-local-path
  */
 function isRelative(uri) {
-  return URL.parse(uri).protocol === null;
+  const { host } = URL.parse(uri);
+  return host === null || host === '';
```
Comment (azu) [inline src/no-dead-link.js]: Windows has a protocol like `C:` .

image

We can use `host` instead of it.

File: src/no-dead-link.js [hunk 2]
```diff
@@ -16,17 +17,23 @@ const URI_REGEXP = /(?:https?:)?\/\/(?:www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-z
...
 }
 
 /**
  * Returns if a given URI indicates a local file.
  * @param {string} uri
  * @return {boolean}
+ * @see https://nodejs.org/api/path.html#path_path_isabsolute_path
  */
 function isLocal(uri) {
+  if (isAbsolute(uri)) {
```
Comment (azu) [inline src/no-dead-link.js]: https://nodejs.org/api/path.html#path_path_isabsolute_path
absolute path is also local.

**Comment by nodaguti** [comment]
Thanks a lot!
